class Volunteer < ActiveRecord::Migration
  def up
    create_table :Volunteer do |t|
      t.string:   :'Date of Application'
      t.string	:'Date of Birth'
      t.string	:'Email Address'
      t.string	:'Phone Numbers'
      t.string	:'Mailing Address'
      t.string	:'County'
      t.string	:'Family Care'
      t.string	:'Ambassador'
      t.string	:'Virtual Volunteer'
      t.string	:'Outlying County Ambassador Program'
      t.string	:'Medical Volunteer'
      t.string	:'Program/Counseling Internship'
      t.string	:'Additional Volunteer Opportunities'
      t.string	:'If you have selected Additional Volunteer Opportunities please specify'
      t.string	:'DaysTimes you will be available to volunteer'
      t.string	:'How did you learn about Scottys House and our Volunteer Program'
      t.string	:'What would you like to gain from your volunteer experience'
      t.string	:'Name of Instructor'
      t.string	:'Name of Organization'
      t.string	:'Other Please explain'
      t.string	:'Name of Employer'
      t.string	:'Class Credit'
      t.string	:'Organization Credit'
      t.string	:'Other'
      t.string	:'Currently Employed'
      t.string	:'Length of Time1'
      t.string	:'Experience with Child Abuse'
      t.string	:'Experience with Foster Care'
      t.string	:'Criminal Juvenile or Family Court System'
      t.string	:'Other Child Service Agencies'
      t.string	:'Organization1'
      t.string	:'Responsibilities1'
      t.string	:'Length of Time2'
      t.string	:'Organization2'
      t.string	:'Responsibilities2'
      t.string	:'Length of Time3'
      t.string	:'Organization3'
      t.string	:'Responsibilities3'
      t.string	:'Length of Time4'
      t.string	:'Organization4'
      t.string	:'Responsibilities4'
      t.string	:'Length of Time5'
      t.string	:'Organization5'
      t.string	:'Responsibilities5'
      t.string	:'Experience with Child Abuse (yes)'
      t.string	:'Experience with Foster Care (yes)'
      t.string	:'Experience with Child Abuse (no)'
      t.string	:'Signature'
      t.string	:'Date'
      t.string	:'Signature_2'
      t.string	:'Date_2'
      t.string	:'Signature_3'
      t.string	:'Date_3'
      t.string	:'Experience with Court (yes)'
      t.string	:'Experience with Foster Care (no)'
      t.string	:'Experience with Child Service (yes)'
      t.string	:'Experience with Child Service (no)'
      t.string	:'Name'
      t.string	:'Speak other language (yes)'
      t.string	:'Speak other language (no)'
      t.string	:'Speak language'
      t.string	:'Literate language'
      t.string	:'Literate other language (no)'
      t.string	:'Literate other language (yes)'
      t.string	:'Experience with blind/deaf persons (yes)'
      t.string	:'Experience with blind/deaf persons (no)'
      t.string	:'Experience with blind/deaf persons'
      t.string	:'Experience with handicap persons (yes)'
      t.string	:'Experience with handicap persons (no)'
      t.string	:'Experience with handicap persons'
      t.string	:'Emergency Name'
      t.string	:'Emergency Phone'
      t.string	:'Emergency Address'
      t.string	:'Emergency Relationship'
    end
  end

  def down
    drop_table :Volunteer
  end
end